/**
 * Created by kasperpeulen on 23/09/14.
 */


var tex2unicode = {
    "α" : "\\alpha",
    "β" : "\\beta" ,
    "\u2071": "^i",
    "\u2074": "^4",
    "\u2075": "^5",
    "\u2076": "^6",
    "\u2077": "^7",
    "\u2078": "^8",
    "\u2079": "^9",
    "\u207A": "^+",
    "\u207B": "^-",
    "\u207C": "^=",
    "\u207D": "^(",
    "\u207E": "^)",
    "\u207F": "^n",
    "\u2080": "_0",
    "\u2081": "_1",
    "\u2082": "_2",
    "\u2083": "_3",
    "\u2084": "_4",
    "\u2085": "_5",
    "\u2086": "_6",
    "\u2087": "_7",
    "\u2088": "_8",
    "\u2089": "_9",
    "\u208A": "_+",
    "\u208B": "_-",
    "\u208C": "_=",
    "\u208D": "_(",
    "\u208E": "_)",
    "\u03B1": "\\alpha ",
    "\u03B2": "\\beta ",
    "\u03B3": "\\gamma ",
    "\u03B4": "\\delta ",
    "\u03B5": "\\epsilon ",
    "\u03B6": "\\zeta ",
    "\u03B7": "\\eta ",
    "\u03B8": "\\texttheta ",
    "\u03B9": "\\iota ",
    "\u03BA": "\\kappa ",
    "\u03BB": "\\lambda ",
    "\u03BC": "\\mu ",
    "\u03BD": "\\nu ",
    "\u03BE": "\\xi ",
    "\u03C0": "\\pi ",
    "\u03C1": "\\rho ",
    "\u03C2": "\\varsigma ",
    "\u03C3": "\\sigma ",
    "\u03C4": "\\tau ",
    "\u03C5": "\\upsilon ",
    "\u03C6": "\\varphi ",
    "\u03C7": "\\chi ",
    "\u03C8": "\\psi ",
    "\u03C9": "\\omega ",
    "\u03D5": "\\phi ",
    "\u03D6": "\\varpi ",
    "\u03DA": "\\Stigma ",
    "\u03DC": "\\Digamma ",
    "\u03DD": "\\digamma ",
    "\u03DE": "\\Koppa ",
    "\u03E0": "\\Sampi ",
    "\u03F0": "\\varkappa ",
    "\u03F1": "\\varrho ",
    "𝔄": "\\mathfrak{A}",
    "𝔅": "\\mathfrak{B}",
    "ℭ": "\\mathfrak{C}",
    "𝔇": "\\mathfrak{D}",
    "𝔈": "\\mathfrak{E}",
    "𝔉": "\\mathfrak{F}",
    "𝔊": "\\mathfrak{G}",
    "ℌ": "\\mathfrak{H}",
    "ℑ": "\\mathfrak{I}",
    "𝔍": "\\mathfrak{J}",
    "𝔎": "\\mathfrak{K}",
    "𝔏": "\\mathfrak{L}",
    "𝔐": "\\mathfrak{M}",
    "𝔑": "\\mathfrak{N}",
    "𝔒": "\\mathfrak{O}",
    "𝔓": "\\mathfrak{P}",
    "𝔔": "\\mathfrak{Q}",
    "ℜ": "\\mathfrak{R}",
    "𝔖": "\\mathfrak{S}",
    "𝔗": "\\mathfrak{T}",
    "𝔘": "\\mathfrak{U}",
    "𝔙": "\\mathfrak{V}",
    "𝔚": "\\mathfrak{W}",
    "𝔛": "\\mathfrak{X}",
    "𝔜": "\\mathfrak{Y}",
    "ℨ": "\\mathfrak{Z}",
    "𝔞": "\\mathfrak{a}",
    "𝔟": "\\mathfrak{b}",
    "𝔠": "\\mathfrak{c}",
    "𝔡": "\\mathfrak{d}",
    "𝔢": "\\mathfrak{e}",
    "𝔣": "\\mathfrak{f}",
    "𝔤": "\\mathfrak{g}",
    "𝔥": "\\mathfrak{h}",
    "𝔦": "\\mathfrak{i}",
    "𝔧": "\\mathfrak{j}",
    "𝔨": "\\mathfrak{k}",
    "𝔩": "\\mathfrak{l}",
    "𝔪": "\\mathfrak{m}",
    "𝔫": "\\mathfrak{n}",
    "𝔬": "\\mathfrak{o}",
    "𝔭": "\\mathfrak{p}",
    "𝔮": "\\mathfrak{q}",
    "𝔯": "\\mathfrak{r}",
    "𝔰": "\\mathfrak{s}",
    "𝔱": "\\mathfrak{t}",
    "𝔲": "\\mathfrak{u}",
    "𝔳": "\\mathfrak{v}",
    "𝔴": "\\mathfrak{w}",
    "𝔵": "\\mathfrak{x}",
    "𝔶": "\\mathfrak{y}",
    "𝔷": "\\mathfrak{z}",
    "𝒜": "\\mathcal{A}",
    "ℬ": "\\mathcal{B}",
    "𝒞": "\\mathcal{C}",
    "𝒟": "\\mathcal{D}",
    "ℰ": "\\mathcal{E}",
    "ℱ": "\\mathcal{F}",
    "𝒢": "\\mathcal{G}",
    "ℋ": "\\mathcal{H}",
    "ℐ": "\\mathcal{I}",
    "𝒥": "\\mathcal{J}",
    "𝒦": "\\mathcal{K}",
    "ℒ": "\\mathcal{L}",
    "ℳ": "\\mathcal{M}",
    "𝒩": "\\mathcal{N}",
    "𝒪": "\\mathcal{O}",
    "𝒫": "\\mathcal{P}",
    "𝒬": "\\mathcal{Q}",
    "ℛ": "\\mathcal{R}",
    "𝒮": "\\mathcal{S}",
    "𝒯": "\\mathcal{T}",
    "𝒰": "\\mathcal{U}",
    "𝒱": "\\mathcal{V}",
    "𝒲": "\\mathcal{W}",
    "𝒳": "\\mathcal{X}",
    "𝒴": "\\mathcal{Y}",
    "𝒵": "\\mathcal{Z}",
    "⁅" : "\\(",
    "⁆" : "\\)",
    // "∕": "\\over ",
    "¦": "\\choose ",
    '❴': "\\{",
    '❵': "\\}",
    '􀀢' :'\\big(',
    '􀀣' :'\\Big(',
    '􀀤' : '\\bigg(',
    '􀀥' : '\\Bigg(',
    '􀀩' : '\\big)',
    '􀀪' : '\\Big)',
    '􀀫' : '\\bigg)',
    '􀀬' : '\\Bigg)',
    '􀀑' :'\\big[',
    '􀀒' :'\\Big[',
    '􀀓' : '\\bigg[',
    '􀀔' : '\\Bigg[',
    '􀀘' : '\\big]',
    '􀀙' : '\\Big]',
    '􀀚' : '\\bigg]',
    '􀀛' : '\\Bigg]',
    '􀀁' :'\\big\\{',
    '􀀂' :'\\Big\\{',
    '􀀃' : '\\bigg\\{',
    '􀀄' : '\\Bigg\\{',
    '􀀈' : '\\big\\}',
    '􀀉' : '\\Big\\}',
    '􀀊' : '\\bigg\\}',
    '􀀋' : '\\Bigg\\}',
    '♡' : '\\heartsuit',
    "≝": "\\stackrel{\\small\\text{def}}{=}",
    '≞': "\\stackrel{\\text{m}}{=}",
    '≟': "\\stackrel{\\text{?}}{=}",
    '⅀': '\\Bbb{\\Sigma}',
    '‾': '\\overline',
    '▁': '\\underline',
    '⏞': '\\overbrace ',
    '\u23DF': '\\underbrace',
    '⨀': '\\bigodot ',
    "\u2102": "\\Bbb{C}",
    "\u210A": "\\mathcal{g}",
    "\u210D": "\\Bbb{H}",
    "\u210F": "\\hslash ",
    "\u2113": "\\ell ",
    "\u2115": "\\Bbb{N}",
    "\u2116": "\\cyrchar\\textnumero ",
    "\u2118": "\\wp ",
    "\u2119": "\\Bbb{P}",
    "\u211A": "\\Bbb{Q}",
    "\u211D": "\\Bbb{R}",
    "\u211E": "\\Elzxrat ",
    "\u2122": "\\texttrademark ",
    "\u2124": "\\Bbb{Z}",
    "\u2126": "\\Omega ",
    "\u2127": "\\mho ",
    "\u2129": "\\ElsevierGlyph{2129}",
    "\u212B": "\\AA ",
    "\u212F": "\\mathcal{e}",
    "\u2134": "\\mathcal{o}",
    "\uD504": "\\mathfrak{A}",
    "\uD505": "\\mathfrak{B}",
    "\uD507": "\\mathfrak{D}",
    "\uD508": "\\mathfrak{E}",
    "\uD509": "\\mathfrak{F}",
    "\uD50A": "\\mathfrak{G}",
    "\uD50D": "\\mathfrak{J}",
    "\uD50E": "\\mathfrak{K}",
    "\uD50F": "\\mathfrak{L}",
    "\uD510": "\\mathfrak{M}",
    "\uD511": "\\mathfrak{N}",
    "\uD512": "\\mathfrak{O}",
    "\uD513": "\\mathfrak{P}",
    "\uD514": "\\mathfrak{Q}",
    "\uD516": "\\mathfrak{S}",
    "\uD517": "\\mathfrak{T}",
    "\uD518": "\\mathfrak{U}",
    "\uD519": "\\mathfrak{V}",
    "\uD51A": "\\mathfrak{W}",
    "\uD51B": "\\mathfrak{X}",
    "\uD51C": "\\mathfrak{Y}",
    "\uD51E": "\\mathfrak{a}",
    "\uD51F": "\\mathfrak{b}",
    "\uD520": "\\mathfrak{c}",
    "\uD521": "\\mathfrak{d}",
    "\uD522": "\\mathfrak{e}",
    "\uD523": "\\mathfrak{f}",
    "\uD524": "\\mathfrak{g}",
    "\uD525": "\\mathfrak{h}",
    "\uD526": "\\mathfrak{i}",
    "\uD527": "\\mathfrak{j}",
    "\uD528": "\\mathfrak{k}",
    "\uD529": "\\mathfrak{l}",
    "\uD52A": "\\mathfrak{m}",
    "\uD52B": "\\mathfrak{n}",
    "\uD52C": "\\mathfrak{o}",
    "\uD52D": "\\mathfrak{p}",
    "\uD52E": "\\mathfrak{q}",
    "\uD52F": "\\mathfrak{r}",
    "\uD530": "\\mathfrak{s}",
    "\uD531": "\\mathfrak{t}",
    "\uD532": "\\mathfrak{u}",
    "\uD533": "\\mathfrak{v}",
    "\uD534": "\\mathfrak{w}",
    "\uD535": "\\mathfrak{x}",
    "\uD536": "\\mathfrak{y}",
    "\uD537": "\\mathfrak{z}",
    "\uD538": "\\Bbb{A}",
    "\uD539": "\\Bbb{B}",
    "\uD53B": "\\Bbb{D}",
    "\uD53C": "\\Bbb{E}",
    "\uD53D": "\\Bbb{F}",
    "\uD53E": "\\Bbb{G}",
    "\uD540": "\\Bbb{I}",
    "\uD541": "\\Bbb{J}",
    "\uD542": "\\Bbb{K}",
    "\uD543": "\\Bbb{L}",
    "\uD544": "\\Bbb{M}",
    "\uD546": "\\Bbb{O}",
    "\uD54A": "\\Bbb{S}",
    "\uD54B": "\\Bbb{T}",
    "\uD54C": "\\Bbb{U}",
    "\uD54D": "\\Bbb{V}",
    "\uD54E": "\\Bbb{W}",
    "\uD54F": "\\Bbb{X}",
    "\uD550": "\\Bbb{Y}",
    "\uD552": "\\Bbb{a}",
    "\uD553": "\\Bbb{b}",
    "\uD554": "\\Bbb{c}",
    "\uD555": "\\Bbb{d}",
    "\uD556": "\\Bbb{e}",
    "\uD557": "\\Bbb{f}",
    "\uD558": "\\Bbb{g}",
    "\uD559": "\\Bbb{h}",
    "\uD55A": "\\Bbb{i}",
    "\uD55B": "\\Bbb{j}",
    "\uD55C": "\\Bbb{k}",
    "\uD55D": "\\Bbb{l}",
    "\uD55E": "\\Bbb{m}",
    "\uD55F": "\\Bbb{n}",
    "\uD560": "\\Bbb{o}",
    "\uD561": "\\Bbb{p}",
    "\uD562": "\\Bbb{q}",
    "\uD563": "\\Bbb{r}",
    "\uD564": "\\Bbb{s}",
    "\uD565": "\\Bbb{t}",
    "\uD566": "\\Bbb{u}",
    "\uD567": "\\Bbb{v}",
    "\uD568": "\\Bbb{w}",
    "\uD569": "\\Bbb{x}",
    "\uD56A": "\\Bbb{y}",
    "\uD56B": "\\Bbb{z}"
}

var tex_to_ctex = function () {
    var textarea = $(activeElement).val();
    var caret = getCaretPosition(activeElement);
    var oldlength = textarea.length;
    for (var b in unicode_to_latex) {
        var a = unicode_to_latex[b];

        a = a.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
        if (a == "\\\\bar"){console.log(a,b);}
        if (/[\u0300-\u036e\u1dc0-\u1dfe\u20d0-\u20fe\ufe20-\ufe2e]/.test(b)) {
            console.log("1");
            var re = new RegExp("(" + a + "){(\\w)}", "g");
            textarea = textarea.replace(re, "$2"+b);
        }
        else{
        var re = new RegExp("(" + a + ")", "g");
        textarea = textarea.replace(re, b);
        }
    }
    var newlength = textarea.length;
    console.log(caret, oldlength, newlength);
    $('#ta').val(textarea);
    if (newlength !== oldlength) {
        setCaretPosition(activeElement, caret + newlength - oldlength);
    }
}